export type UserModel = {
    id: string;
    organization: string;
    name: string;
    email: string;
    statusCode: string;
    phone: string;
    dateJoined: string;
    facebook: string;
    twitter: string;
    userCode: string;
    company: string;
    gender: string;
    levelOfEducation: string;
    employmentStatus: string;
    marritalStatus: string;
    bvn: string;
    children: string;
    officeMail: string;
    sectorOfEmployment: string;
    monthlyIncome: string;
    loanRepayment: string;
    typeOfResidence: string;
    instagram: string;
  };